//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVERAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int questionId { get; set; }
        public Nullable<int> subjectId { get; set; }
        public string question1 { get; set; }
        public byte[] picture { get; set; }
        public string firstAnswer { get; set; }
        public string secondAnswer { get; set; }
        public string thirdAnswer { get; set; }
        public string fourthAnswer { get; set; }
        public string correctAnswer { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
