//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVERAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KoursovaEntities : DbContext
    {
        public KoursovaEntities()
            : base("name=KoursovaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<UserAnswer> UserAnswers { get; set; }
    
        public virtual int UserAdd(string username, Nullable<int> memberId, string email, string passwordReg)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordRegParameter = passwordReg != null ?
                new ObjectParameter("passwordReg", passwordReg) :
                new ObjectParameter("passwordReg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UserAdd", usernameParameter, memberIdParameter, emailParameter, passwordRegParameter);
        }
    }
}
