//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectKoursova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int registrationId { get; set; }
        public string username { get; set; }
        public Nullable<int> memberId { get; set; }
        public string email { get; set; }
        public string passwordReg { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
